fix: add color scheme for a visited link
yandex-cloud/uikit pull request #243
Opened 2022-07-14 13:26 UTC by krozhkov

2022-07-14 14:04 UTC, ogonkov commented on src/components/Link/Link.scss
> +        &:visited {
visited should be before hover

2022-07-15 09:08 UTC, ValeraS requested changes

2022-07-15 09:08 UTC, ValeraS commented on styles/colors/text/light.scss
> +    --yc-color-text-link-visited-hover: var(--yc-color-private-blue-800);
the same as above

2022-07-21 08:24 UTC, ValeraS approved these changes

2022-07-21 09:28 UTC, merged