Add social components and mob stores bages
yandex-cloud/uikit pull request #275
Opened 2022-07-28 07:35 UTC by gorgeousvlad

2022-07-28 09:43 UTC, ogonkov commented on src/components/ShareTooltip/README.md
> +Компонента для шеринга
It should be in english

2022-07-28 09:43 UTC, ogonkov commented on src/components/ShareTooltip/ShareList/ShareList.scss
> +@import '../../variables.scss';
```suggestion
@use '../../variables.scss';
```

2022-07-28 09:43 UTC, ogonkov commented on src/components/ShareTooltip/ShareList/ShareList.tsx
> +                <span className={b('copy-label')}>{label}</span>
There is no styles for this span?

2022-07-28 09:43 UTC, ogonkov commented on src/components/ShareTooltip/ShareList/ShareList.tsx
> +        await copyToClipboard(this.props.url);
uikit got component for this

2022-07-28 09:43 UTC, ogonkov commented on src/components/ShareTooltip/ShareTooltip.scss
> +@import '../variables.scss';
```suggestion
@use '../../../styles/mixins.scss';
@use '../variables.scss';
```

2022-07-28 09:43 UTC, ogonkov commented on src/components/ShareTooltip/__stories__/ShareTooltip.stories.tsx
> +            description: 'заголовок к ссылке',
english

2022-07-28 10:13 UTC, resure commented on src/components/StoreBadge/StoreBadge.tsx
> +export function StoreBadge({platform, lang = 'ru', className, onClick, url}: StoreBadgeProps) {
default should be 'en'

2022-07-28 10:16 UTC, resure commented
- This PR lacks description
- Why two components are being added in one PR, are they inseparable?
- Documentation and comments should be translated into English

2022-07-28 17:58 UTC, ogonkov commented on src/components/ShareTooltip/SocialShareLink/SocialShareLink.tsx
> +                return `https://t.me/share/url?${stringify({url, text: title})}`;
Can we use `URL` instead, please? It do same thing, but without external dependency

```suggestion
                const url = new URL('https://t.me/share/url');
                url.searchParams.set('url', url);
                url.searchParams.set('text', title);
                return url.toString();
```

2022-07-28 18:01 UTC, ogonkov commented on src/components/ShareTooltip/__stories__/ShareTooltip.stories.tsx
> +    args: {...shareTooltipDefaultProps},
Can we add `socialNets` to storybook?

2022-07-28 18:01 UTC, ogonkov commented on src/components/ShareTooltip/__stories__/ShareTooltip.stories.tsx
> +import {Meta, Story} from '@storybook/react';
```suggestion
import {ComponentMeta, ComponentStory} from '@storybook/react';
```

2022-07-29 07:28 UTC, gorgeousvlad commented on src/components/ShareTooltip/__stories__/ShareTooltip.stories.tsx
> +    args: {...shareTooltipDefaultProps},
What do you mean?

2022-07-29 09:58 UTC, gorgeousvlad commented
> * Why two components are being added in one PR, are they inseparable?
Do we have a rule that prohibits it?

2022-07-29 13:05 UTC, ogonkov commented
@resure @amje do we need hardcoded social networks with icons in uikit?

2022-07-29 13:09 UTC, resure commented
> do we need hardcoded social networks with icons in uikit?

I don't have strong opinion on this matter. In theory, such separation sounds logical, but to be practically useful we'll still need to somehow provide set with widely used icons with or alongside the uikit.

2022-07-29 13:16 UTC, amje commented
> @resure @amje do we need hardcoded social networks with icons in uikit?

I think no, uikit is not the place to store them. But, currently it is the only place in our OS to share components.

2022-07-29 13:17 UTC, ogonkov commented on src/components/ShareTooltip/ShareList/ShareList.tsx
> +                        <span>{label}</span>
What is purpose of this span?

2022-07-29 13:17 UTC, ogonkov commented on src/components/ShareTooltip/SocialShareLink/SocialShareLink.tsx
> +            <Button view="flat" size="l" href={url} target="_blank" className={b(null, className)}>
Can you add `extraProps={{'aria-label': i18n('label_share', {name: SocialNetwork[type]})}}` please? With text like "Share to %s"

2022-07-29 13:17 UTC, ogonkov commented on src/components/StoreBadge/StoreBadge.scss
> +            content: url('data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTE5IiBoZWlnaHQ9IjQwIiBmaWxsPSJub25lIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPjxyZWN0IHg9Ii41IiB5PSIuNSIgd2lkdGg9IjExOCIgaGV
Do we really need it inlined?

2022-07-29 13:49 UTC, ogonkov commented on src/components/ShareTooltip/ShareList/ShareList.tsx
> +    // eslint-disable-next-line react/sort-comp
Why?

2022-07-29 13:49 UTC, ogonkov commented on src/components/utils/copy-to-clipboard.ts
> +export async function copyToClipboard(text: string) {
It still used somewhere?

2022-07-29 14:22 UTC, resure commented
> I think no, uikit is not the place to store them. But, currently it is the only place in our OS to share components.

Then we can adopt here same strategy as with changelogs, stories, etc. — keep it in uikit for now and later move to some additional library/libraries.

2022-07-29 14:47 UTC, amje requested changes

2022-07-29 14:47 UTC, amje commented on src/components/ShareTooltip/ShareList/ShareList.tsx
> +export interface ShareListDefaultProps {
Let's remove this export, we don't need it outside

2022-07-29 14:47 UTC, amje commented on src/components/ShareTooltip/ShareTooltip.tsx
> +export interface ShareTooltipDefaultProps extends ShareListDefaultProps {
remove export

2022-07-29 14:47 UTC, amje commented on src/components/ShareTooltip/ShareTooltip.tsx
> +export const shareTooltipDefaultProps: ShareTooltipDefaultProps = {
remove export

2022-07-29 14:47 UTC, amje commented on src/components/ShareTooltip/ShareTooltip.tsx
> +export class ShareTooltip extends React.PureComponent<ShareTooltipInnerProps> {
Consider rewriting new components with FC instead of classes.

2022-07-29 14:47 UTC, amje commented on src/components/ShareTooltip/SocialShareLink/SocialShareLink.tsx
> +                throw new Error(`Unknown share type: ${type}`);
It's bad to throw in render, maybe console message will be enough?

2022-07-29 14:47 UTC, amje commented on src/components/ShareTooltip/constants.ts
> +export enum LayoutDirections {
enum name should be singular

2022-07-29 14:47 UTC, amje commented on src/components/ShareTooltip/constants.ts
> +    column = 'column',
enum item name should be capitalized

2022-07-29 14:47 UTC, amje commented on src/components/StoreBadge/README.md
> +| className | `String`        |          |         | Class элемента       |
Please translate to english

2022-07-29 14:47 UTC, amje commented on src/components/StoreBadge/StoreBadge.tsx
> +export type BadgeLang = 'ru' | 'en';
We have enum `Lang`, no need to introduce another one

2022-07-29 14:47 UTC, amje commented on src/components/StoreBadge/StoreBadge.tsx
> +export type BadgePlatform = Platform.ANDROID | Platform.IOS;
`BadgePlatform` -> `StoreBadgePlatform`

2022-07-29 14:47 UTC, amje commented on src/components/icons/Link.tsx
> +                fill="currentColor"
parent svg already has it

2022-07-29 14:47 UTC, amje commented on src/components/icons/Share.tsx
> +                fill="currentColor"
parent svg already has it

2022-07-29 14:47 UTC, amje commented on src/components/utils/copy-to-clipboard.ts
> +export async function copyToClipboard(text: string) {
We have separate component for this

2022-07-29 14:47 UTC, amje commented on src/demo/ShareTooltip/ShareTooltip.scss
> +@import '../../components/variables.scss';
`src/demo` folder is only for technical components. Put this under `__stories__` folder

2022-07-29 14:47 UTC, amje commented on src/demo/ShareTooltip/index.tsx
> +import React from 'react';
All files should be moved under `__stories__` of ShareTooltip.  See Button stories for example of showcase demo

2022-08-01 09:32 UTC, ogonkov approved these changes

2022-08-02 07:49 UTC, merged