feat: migrate Toaster component
yandex-cloud/uikit pull request #46
Opened 2022-01-17 10:29 UTC by Raubzeug

2022-01-20 09:18 UTC, ValeraS requested changes

2022-01-20 09:18 UTC, ValeraS commented on src/components/Toaster/Toast/Toast.tsx
> +    };
let's extract this function and rename

```typescript
function renderActions({actions, onClose})
```

2022-01-20 09:18 UTC, ValeraS commented on src/components/Toaster/Toast/Toast.tsx
> +    };
let's extract this function:

```typescript
function renderIcon({type})
```

2022-01-20 11:27 UTC, ValeraS requested changes

2022-01-20 11:27 UTC, ValeraS commented on src/components/Toaster/Toast/Toast.tsx
> +} {
don't have to specify return type, typescript can infers it automatically
```suggestion
function useCloseOnTimeout({onClose, timeout}: UseCloseOnTimeoutProps) {
```

2022-01-20 11:27 UTC, ValeraS commented on src/components/Toaster/Toast/Toast.tsx
> +    });
```suggestion
    const timeout = allowAutoHiding ? props.timeout || DEFAULT_TIMEOUT : undefined
    const closeOnTimeoutProps = useCloseOnTimeout({onClose: handleClose, timeout});
```

2022-01-20 11:27 UTC, ValeraS commented on src/components/Toaster/Toast/Toast.tsx
> +            styles.position = 'relative';
maybe set it by css class, for example, add mod `creating`

2022-01-20 11:27 UTC, ValeraS commented on src/components/Toaster/Toast/Toast.tsx
> +        }
let's move it to useHeight, and change:

```typescript
function useToastHeight({isOveride}): {style, ref}

const heightProps = useToastHeight({isOveride});
return <div {...heightProps}>
```

2022-01-20 11:27 UTC, ValeraS commented on src/components/Toaster/Toast/Toast.tsx
> +        containerProps: {onAnimationEnd},
```suggestion
        containerProps: statusProps,
```

2022-01-20 11:27 UTC, ValeraS commented on src/components/Toaster/Toast/Toast.tsx
> +        >
```suggestion
        <div
            className={b(mods, className)}
            {...statusProps}
            {...heightProps}
            {...closeOnTimeoutProps}
        >
```

2022-01-20 11:27 UTC, ValeraS commented on src/components/Toaster/Toast/Toast.tsx
> +            {getCloseButton()}
```suggestion
            {isClosable && (
             <Button
                view="flat-secondary"
                size="s"
                style={{position: 'absolute', top: 10, right: 10}}
                onClick={handleClose}
            >
                <Icon data={CrossIcon} />
            </Button>
       )}
```

2022-01-20 14:14 UTC, ValeraS requested changes

2022-01-20 14:14 UTC, ValeraS commented on src/components/Toaster/Toast/Toast.tsx
> +    }, [isOverride, getToastHeight]);
This doesn't  work if override twice with different content. 

```suggestion
    React.useEffect(() => {
        if (isOverride) {
            setHeight(getToastHeight());
        }
    });
```

2022-01-21 15:58 UTC, ValeraS approved these changes
one more small fix and I think it's ready to go

2022-01-21 15:58 UTC, ValeraS commented on src/components/Toaster/Toast/Toast.tsx
> +    }, [ref]);
```suggestion
    }, []);
```

2022-01-24 11:59 UTC, amje requested changes

2022-01-24 11:59 UTC, amje commented on src/components/Toaster/Toast/Toast.tsx
> +    shown = 'shown',
Enum name starts with capital letter

2022-01-24 11:59 UTC, amje commented on src/components/Toaster/__stories__/ToasterShowcase.tsx
> +            title: 'Оплата успешно произведена',
Let's rewrite all file texts in english

2022-01-24 13:19 UTC, amje approved these changes

2022-01-24 13:23 UTC, merged