feat: add Select component
yandex-cloud/uikit pull request #72
Opened 2022-01-30 18:35 UTC by korvin89

Add `Select` component (#16)

2022-02-02 14:23 UTC, amje requested changes

2022-02-02 14:23 UTC, amje commented on src/components/unstable/Select/components/Control/Control.tsx
> +Control.displayName = 'Control';
SelectControl?

2022-02-02 14:23 UTC, amje commented on src/components/unstable/Select/tech-components.tsx
> +export const Optgroup: React.FC<SelectOptgroup> = () => null;
Lets name this as `OptionGroup`

2022-02-03 15:03 UTC, korvin89 commented on src/components/unstable/Select/__stories__/SelectShowcase.tsx
> +const MODE = {
There is no need to use enum in this case. We don`t need type. Also enum transpiling into horrible js construction

2022-02-04 13:32 UTC, amje requested changes

2022-02-04 13:32 UTC, amje commented on src/components/unstable/Select/utils.ts
> +export const getSelectPopupItemHeight = (args: {
"Select" part can be omitted like in the function below `getPopupVerticalOffset `

2022-02-04 13:32 UTC, amje commented on src/components/unstable/Select/utils.ts
> +export const getSelectPopupHeight = (args: {
same

2022-02-04 13:32 UTC, amje commented on src/components/unstable/Select/utils.ts
> +    selectPopupHeight: number;
just popupHeight will be enough

2022-02-04 13:32 UTC, amje commented on src/components/unstable/Select/components/SelectControl/SelectControl.scss
> +        var(--yc-button-border-radius)
button -> select

2022-02-04 13:32 UTC, amje commented on src/components/unstable/Select/components/SelectControl/SelectControl.scss
> +        (#{$block}_size_s, #{$block}_size_m, #{$block}_size_l, #{$block}_size_xl),
This results in four exact chunks of code. Just `$block` will be enough

2022-02-04 13:40 UTC, amje commented on src/components/unstable/Select/__stories__/SelectShowcase.tsx
> +const MODE = {
Then it's a namespace for constants and should be named as `Mode`. `MODE.CODE` looks a bit screamy.

2022-02-04 13:42 UTC, amje commented on src/components/unstable/Select/__stories__/SelectShowcase.scss
> +$block: '.#{$ns}select-showcase';
ok, but it is not necessary for demos, `bem-cn-lite` could be used directly here

2022-02-04 15:49 UTC, amje approved these changes

2022-02-04 15:57 UTC, merged